### ISSUE TITLE
The `panic_handler` feature is not required as the latest nightly

### ISSUE THREAD

**Issue by japaric** [korken89/panic-halt#2]
Removing it will make this crate compile on the upcoming 1.30-beta and stable 1.30 releases.

When you release a new version without the feature gate please increase the minor version (i.e. release it as v0.2.0) so that you won't break old nightlies that are using the v0.1.x series.

Also, could you add `panic-handler` to the list of keywords for this crate? I'd like to move from the `panic-impl` keyword to `panic-handler` since the name of the feature changed.

**Comment by korken89** [comment]
Awesome that this is approaching and thanks for the heads up! Fixed in cc75f871daf97e2cb25acc6571f2b0e49f4f9786
