### ISSUE TITLE
`atomic::compiler_fence` prevents optimizing out the panic info

### ISSUE THREAD

**Issue by jonas-schievink** [korken89/panic-halt#3]
I realize this is needed to work around https://github.com/rust-lang/rust/issues/28728, but I just wanted to note that the `compiler_fence` apparently prevents the compiler from optimizing out the `PanicInfo` passed to the handler. All panic messages stay in the executable.

Manually removing the call to `atomic::compiler_fence` results in the panic info being removed like I'd expect.

**Comment by korken89** [comment]
Hi, indeed this is there due to that.
The easy fix is to use `panic-abort`, if you find a different way to do this I'm very open to include it :)

**Comment by reitermarkus** [comment]
Seems like https://github.com/rust-lang/rust/issues/28728 was recently fixed, FYI.

**Comment by romancardenas** [comment]
Would it be possible to release a 1.0.0 version with something like this now?

```rust
#[inline(never)]
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}
```

I'm not sure about which MSRV applies, but being fixed since 2021, it doesn't look like an issue
