### ISSUE TITLE
All docs fail to build

### ISSUE THREAD

**Issue by piegamesde** [korken89/panic-halt#4]
https://docs.rs/crate/panic-halt/0.2.0

![image](https://user-images.githubusercontent.com/14054505/131500942-700c7b4a-94bd-45b8-9fd6-0d3a45818427.png)

**Comment by korken89** [comment]
Hmm, this seems odd, I have no issues at all building the docs locally.
It seems `docs.rs` are building the docs with a really old rustc version (1.28) in which `#[panic_handler]` did not exist.

Not sure how to fix this unfortunately.

**Comment by piegamesde** [comment]
The last log I could find is from 2018. Triggering a rebuild maybe could resolve it. Otherwise, we'll have to file an [upstream issue](https://github.com/rust-lang/docs.rs/issues/new/choose).

**Comment by korken89** [comment]
I have logged an upstream issue.

**Comment by romancardenas** [comment]
I think this issue can be closed, as docs seem to work now
