### ISSUE TITLE
panic-halt does not disable interrupts

### ISSUE THREAD

**Issue by Sympatron** [korken89/panic-halt#7]
As long as interrupts stay enabled, a panic will not really halt the program, but just anything with equal or less priority on MCUs and it won't halt other threads in `std` either. Is this intended behavior?

I think `panic-abort` will crash the whole program, so this might be unexpected.

**Comment by korken89** [comment]
This is intended behavior, mostly here to give a stable symbol to help debugging.
I'm open to adding feature flags if you want more control over the halting behavior!

**Comment by Sympatron** [comment]
I don't how to handle this in a cross platform way, so it's probably best to leave it as it is. If one needs custom halting behavior they should probably just write their own panic handler. It's just a few lines of code after all.

It may be helpful to document this behavior though.
